name: Workbench Service

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "workbench"
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push versioned Docker image
        run: |
          version=$( cat ./services/workbench/version.txt )
          docker build ./services/workbench --tag ghcr.io/${{ github.repository }}/workbench:$version
          docker push ghcr.io/${{ github.repository }}/workbench:$version
      - name: Retag and push latest Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          version=$( cat ./services/workbench/version.txt )
          docker tag ghcr.io/${{ github.repository }}/workbench:$version \
                     ghcr.io/${{ github.repository }}/workbench:latest 
          docker push ghcr.io/${{ github.repository }}/workbench:latest
